import {RulesVersion} from "../models/RulesVersion.model";

export const RULES_VERSIONS: RulesVersion[] = [
  {
    versionNumber: 18,
    amendmentDay: 24,
    amendmentMonth: 1,
    amendmentYear: 2022,
    future: true,
  },
  {
    versionNumber: 17,
    amendmentDay: 18,
    amendmentMonth: 10,
    amendmentYear: 2021,
    current: true,
  },
  {
    versionNumber: 16,
    amendmentDay: 28,
    amendmentMonth: 6,
    amendmentYear: 2021,
  },
  {
    versionNumber: 15,
    amendmentDay: 24,
    amendmentMonth: 5,
    amendmentYear: 2021,
  },
  {
    versionNumber: 14,
    amendmentDay: 10,
    amendmentMonth: 5,
    amendmentYear: 2021,
  },
  {
    versionNumber: 13,
    amendmentDay: 9,
    amendmentMonth: 11,
    amendmentYear: 2020,
  },
  {
    versionNumber: 12,
    amendmentDay: 17,
    amendmentMonth: 8,
    amendmentYear: 2020,
  },
  {
    versionNumber: 11,
    amendmentDay: 23,
    amendmentMonth: 9,
    amendmentYear: 2013,
  },
  {
    versionNumber: 10,
    amendmentDay: 9,
    amendmentMonth: 5,
    amendmentYear: 2005,
  },
  {
    versionNumber: 9,
    amendmentDay: 22,
    amendmentMonth: 2,
    amendmentYear: 1999,
  },
  {
    versionNumber: 8,
    amendmentDay: 16,
    amendmentMonth: 11,
    amendmentYear: 1998,
  },
  {
    versionNumber: 7,
    amendmentDay: 2,
    amendmentMonth: 1,
    amendmentYear: 1996,
    showNotes: true,
  },
  {
    versionNumber: 6,
    amendmentDay: 18,
    amendmentMonth: 11,
    amendmentYear: 1991,
    showNotes: true,
    missingInfo: true,
  },
  {
    versionNumber: 5,
    amendmentDay: 26,
    amendmentMonth: 6,
    amendmentYear: 1989,
    showNotes: true,
    missingInfo: true,
  },
  {
    versionNumber: 4,
    amendmentDay: 3,
    amendmentMonth: 4,
    amendmentYear: 1989,
    showNotes: true,
    missingInfo: true,
  },
  {
    versionNumber: 3,
    amendmentDay: 19,
    amendmentMonth: 12,
    amendmentYear: 1988,
    showNotes: true,
    missingInfo: true,
  },
  {
    versionNumber: 2,
    amendmentDay: 6,
    amendmentMonth: 7,
    amendmentYear: 1987,
    showNotes: true,
    missingInfo: true,
  },
  {
    versionNumber: 1,
    amendmentDay: 15,
    amendmentMonth: 6,
    amendmentYear: 1987,
    showNotes: true,
    missingInfo: true,
  },
];
